Updated With Jayatana

diff --git a/jdebianizer b/jdebianizer
--- a/jdebianizer
+++ b/jdebianizer
@@ -10,7 +10,7 @@
 #			Script is not compliant with ZSH.
 # Dependencies	:	md5deep, whiptail, zenity		
 # Author 	: 	Hanine HAMZIOUI <hanynowsky@gmail.com>
-# Version 	: 	1.0
+# Version 	: 	1.0a
 # License	:	GNU GPL V3+
 # Date created	:	Wed 14 Nov 2012 12:40:32 AM WET 
 
@@ -34,7 +34,66 @@ CONFIGFILE=$HOME/.config/jdebianizer.conf
 TEMPFILE=$HOME/Desktop/jdtemp.log
 ZWINICON=/usr/share/icons/hicolor/48x48/apps/distributor-logo.png
 
-# -------------- ARGS ---------------------
+# ----------------JAYATANA INSTALLER --------
+DESKTOP=$(echo $XDG_CURRENT_DESKTOP)
+JDKPATH=`echo $JAVA_HOME | grep .`
+USERHOME=`echo $HOME`
+JAYATANADD="http://java-swing-ayatana.googlecode.com/svn/tags/1.2.4/jayatana"
+
+# INSTALL 
+INSTALLCOM () {
+sudo apt-get -y install openjdk-7-jdk libunity-dev libxt-dev gcc make ant subversion 
+sudo update-java-alternatives -s java-1.7.0-openjdk-amd64 
+svn checkout $JAYATANADD 
+sudo ant install -buildfile $USERHOME/jayatana/build.xml -v
+sudo ant config -v 
+sudo update-alternatives --config java 
+sudo update-alternatives --config javac
+sudo ant install -Djava.home.7=/usr/lib/jvm/java-7-openjdk-amd64 -f $USERHOME/jayatana/build.xml -v -l $USERHOME/Desktop/jayatana-stall.log
+sudo ant config -Djava.home.7=$JDKPATH -buildfile ~/jayatana/build.xml -v -l $USERHOME/Desktop/jayatana-stall.log
+}
+
+# UNINSTALL
+UNINSTALLCOM (){
+sudo ant deinstall -buildfile $USERHOME/jayatana/build.xml -v
+sudo ant deconfig -buildfile $USERHOME/jayatana/build.xml -v
+sudo ant deconfig -Djava.home.7=$JDKPATH -buildfile $USERHOME/jayatana/build.xml -v -logfile $USERHOME/Desktop/jayatana-stall.log
+}
+
+# DELETE Jayatana Folder created by subversion checkout
+UNDIR() {
+whiptail --yesno "Delete Jayatana Folder too?" "$LINES" "$COLUMNS" --backtitle "Ubuntu Global Menu Support for Java Swing Applications" --title "JDebianizer"
+if [ "$?" = 0 ]; then mv $HOME/jayatana $HOME/.local/share/Trash/files/
+elif [ "$?" = 1 ]; then echo "Jayatana Folder is kept by $USER , you can delete it later : ~/jayatana";
+else echo "Jayatana Folder is kept by $USER , you can delete it later : ~/jayatana";
+fi
+}
+
+# COMMON
+COMMON() {
+echo "$JDKPATH : is your default JDK. Version: " 
+echo `java -version`
+}
+
+# PROMPT INSTALL
+RUNINST() {
+eval COMMON;
+read -p "Enter ( i ) to install or ( u ) to uninstall : " option
+whiptail --yesno "Install/Uninstall Jayatana" "$LINES" "$COLUMNS" --yes-button "Install" --no-button "Uninstall" --backtitle "Ubuntu Global Menu Support for Java Swing Applications" --title "JDebianizer"
+if [ "$?" = 0  ]; then eval INSTALLCOM
+elif [ "$?" = 1 ]; then eval UNINSTALLCOM;eval UNDIR;
+else echo "Aborted by $USER";
+fi
+}
+
+# JAYATANA MAIN
+jayamain() {
+if [ "${DESKTOP,,}" = "unity" ]; then eval RUNINST
+else echo "Your Desktop environment is ${DESKTOP}. You cannot Install Jayatana. (Required: Unity Shell)"
+fi
+}
+
+# -------------------------- ARGS -----------
 argfu(){
 for arg in $@
 do
@@ -86,9 +145,12 @@ tput cup 13 15
 echo "1. Start JDebianzer"
 tput cup 14 15
 echo "2. Exit JDebianzer"
-tput cup 16 15
-read -p "Enter your choice [ 1 / 2]  " choice
+tput cup 15 15
+echo "3. Install Jayatana (Ubuntu Global Menu Support for Java Swing Applications)"
+tput cup 17 15
+read -p "Enter your choice [ 1 / 2 / 3 ]  " choice
 if [ "$choice" = "1" ] ; then echo "Starting JDebianizer..."
+elif [ "$choice" = "3" ] ; then echo "Starting Jayatana installer..."; eval jayamain
 else echo "exiting JDebianizer"; exit 0;
 fi
 tput clear
